### ISSUE TITLE
Hosting requests do not seem to support trailing `/` in repo URLs

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/repository-permissions-updater#3849] opened 2024-03-28 07:31 UTC
Potential culprit: https://github.com/jenkins-infra/repository-permissions-updater/blob/f33244e478b6b9288a395ddc6e59a569dd72be86/src/main/java/io/jenkins/infra/repository_permissions_updater/hosting/Hoster.java#L75

Log output in https://github.com/jenkins-infra/repository-permissions-updater/actions/runs/8328738115/job/22789409098:
```
[main] INFO io.jenkins.infra.repository_permissions_updater.hosting.Hoster - Approving hosting request 3830
[main] INFO io.jenkins.infra.repository_permissions_updater.hosting.Hoster - Forking people-view-plugin/
[main] WARN io.jenkins.infra.repository_permissions_updater.hosting.Hoster - No such repository: people-view-plugin/
[main] ERROR io.jenkins.infra.repository_permissions_updater.hosting.Hoster - Hosting request failed to fork repository on Github
```

Original content of #3830:

> ### Repository URL
> 
> https://github.com/daniel-beck/people-view-plugin/
> 
> ### New Repository Name
> 
> people-view-plugin

**Comment by NotMyFault** [comment] 2024-03-29 07:49
Duplicate of https://github.com/jenkins-infra/repository-permissions-updater/issues/2586

**Closed by NotMyFault** 2024-03-29 07:49 UTC
